## Import Packages

In [2]:
import pandas as Endy_pd

## Import Data

In [3]:
Endy_data = Endy_pd.read_csv('Online Retail Data.csv', header = 0)
Endy_data

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

## Query Dengan Logical Expression

In [7]:
#Mengakses data yang mengandung sebuah kata dan kondisi lainnya
Endy_data[(Endy_data['product_name'].str.contains('TEA')) & (Endy_data['quantity'] == 1)]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
253,493442,37333,"RETRO ""TEA FOR ONE""",1,2010-01-04 13:36:00,4.95,13821.0
311,493443,21528,DAIRY MAID TRADITIONAL TEAPOT,1,2010-01-04 13:39:00,6.95,14527.0
337,493443,47566B,TEA TIME PARTY BUNTING,1,2010-01-04 13:39:00,4.65,14527.0
528,493536,21035,SET/2 RED SPOTTY TEA TOWELS,1,2010-01-04 15:29:00,2.95,17841.0
576,493536,20747,PICCADILLY TEA SET,1,2010-01-04 15:29:00,14.95,17841.0
...,...,...,...,...,...,...,...
461373,539958,22309,TEA COSY RED STRIPE,1,2010-12-23 13:26:00,5.06,NaN
461383,539958,22358,KINGS CHOICE TEA CADDY,1,2010-12-23 13:26:00,5.91,NaN
461472,539958,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-23 13:26:00,5.91,NaN
461762,539991,22891,TEA FOR ONE POLKADOT,1,2010-12-23 16:49:00,4.25,NaN
461763,539991,22649,STRAWBERRY FAIRY CAKE TEAPOT,1,2010-12-23 16:49:00,4.95,NaN

In [9]:
#Mengakses data hanya mengandung suatu kata tertentu
Endy_data['product_name'].str.contains('RED')

0         False
1         False
2         False
3         False
4         False
          ...
461768    False
461769    False
461770    False
461771    False
461772     True
Name: product_name, Length: 461773, dtype: object

In [11]:
#Mengakses data yang mengandung sebuah kata menggunakan or
Endy_data[(Endy_data['product_name'].str.contains('TEA')) | (Endy_data['product_name'].str.contains('COFFE'))]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
10,493414,21527,RETRO SPOT TRADITIONAL TEAPOT,12,2010-01-04 10:28:00,6.95,14590.0
12,C493415,21527,RETRO SPOT TRADITIONAL TEAPOT,-3,2010-01-04 10:33:00,7.95,14590.0
22,493427,79000,MOROCCAN TEA GLASS,12,2010-01-04 10:43:00,0.85,13287.0
58,C493430,21527,RETRO SPOT TRADITIONAL TEAPOT,-1,2010-01-04 11:43:00,7.95,14680.0
102,493432,22072,TEA CUP AND SAUCER RETRO SPOT,2,2010-01-04 12:30:00,3.75,14680.0
...,...,...,...,...,...,...,...
461653,539986,22302,COFFEE MUG PEARS DESIGN,5,2010-12-23 15:21:00,2.55,NaN
461744,539988,47559B,TEA TIME OVEN GLOVE,2,2010-12-23 16:06:00,1.25,18116.0
461758,539991,22970,LONDON BUS COFFEE MUG,2,2010-12-23 16:49:00,2.55,NaN
461762,539991,22891,TEA FOR ONE POLKADOT,1,2010-12-23 16:49:00,4.25,NaN
461763,539991,22649,STRAWBERRY FAIRY CAKE TEAPOT,1,2010-12-23 16:49:00,4.95,NaN

In [15]:
#Mengakses data yang mengandung sebuah kata menggunakan or dan dalam kondisi tertentu
Endy_data[
    ((Endy_data['product_name'].str.contains('TEA')) | (Endy_data['product_name'].str.contains('COFFE')))
    & (Endy_data['price'] > 7)]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
12,C493415,21527,RETRO SPOT TRADITIONAL TEAPOT,-3,2010-01-04 10:33:00,7.95,14590.0
58,C493430,21527,RETRO SPOT TRADITIONAL TEAPOT,-1,2010-01-04 11:43:00,7.95,14680.0
104,493432,21527,RETRO SPOT TRADITIONAL TEAPOT,5,2010-01-04 12:30:00,7.95,14680.0
109,493432,37503,TEA TIME CAKE STAND IN GIFT BOX,2,2010-01-04 12:30:00,10.75,14680.0
124,493433,37503,TEA TIME CAKE STAND IN GIFT BOX,6,2010-01-04 12:51:00,10.75,14709.0
...,...,...,...,...,...,...,...
460396,539750,22139,RETROSPOT TEA SET CERAMIC 11 PC,1,2010-12-21 15:40:00,11.02,NaN
460582,539753,37500,TEA TIME TEAPOT IN GIFT BOX,1,2010-12-21 15:48:00,9.95,NaN
460589,539753,20748,KENSINGTON COFFEE SET,1,2010-12-21 15:48:00,12.75,NaN
461041,539955,22114,HOT WATER BOTTLE TEA AND SYMPATHY,2,2010-12-23 12:13:00,9.32,NaN
461156,539958,21528,DAIRY MAID TRADITIONAL TEAPOT,1,2010-12-23 13:26:00,13.57,NaN

In [16]:
#Akses beberapa kolom
Endy_data[['product_name', 'price']]

                           product_name  price
0               This is a test product.   4.50
1               RETRO SPOTS BUTTER DISH   4.25
2               This is a test product.   4.50
3       PANDA AND BUNNIES STICKER SHEET   0.85
4        ELEPHANT TOY WITH BLUE T-SHIRT   3.75
...                                 ...    ...
461768   4 WILDFLOWER BOTANICAL CANDLES   1.25
461769            GRAND CHOCOLATECANDLE   1.45
461770    FLOWER VINE RAFFIA FOOD COVER   3.75
461771          FELT FARM ANIMAL RABBIT   1.25
461772            RED RETROSPOT PEG BAG   2.10

[461773 rows x 2 columns]